declare const mermaid: any;

export type Edge = [string, string];

// mermaid.initialize({ startOnLoad: false });
mermaid.initialize({ startOnLoad: false, suppressErrorRendering: true });
export const codeBox = document.getElementById('code') as HTMLTextAreaElement;
export const diagramBox = document.getElementById('diagram')!;
export const errorBox = document.getElementById('error')!;
export const errorLog = document.getElementById('errorLog')!;
export const statusBox = document.getElementById('status')!;
export const selectBox = document.getElementById('diagramSelect') as HTMLSelectElement;
export const drawer = document.getElementById('drawer')!;
export const drawerToggle = document.getElementById('drawerToggle')!;
export const openFileBtn = document.getElementById('openFileBtn')!;
export const openFileInput = document.getElementById('openFileInput') as HTMLInputElement;
export const mainBox = document.getElementById('main')!;
export const outputBox = document.getElementById('output')!;
export const phoneDiagramBox = document.getElementById('phoneDiagram')!;
export const logBtn = document.getElementById('logBtn')!;
export const logBox = document.getElementById('logBox')!;
export const previousDecisionBtn = document.getElementById('previousDecisionBtn')!;
export const nextDecisionBtn = document.getElementById('nextDecisionBtn')!;
export const decisionCounter = document.getElementById('decisionCounter')!;
export const zoomInBtn = document.getElementById('zoomInBtn') as HTMLButtonElement;
export const zoomOutBtn = document.getElementById('zoomOutBtn') as HTMLButtonElement;
export const zoomResetBtn = document.getElementById('zoomResetBtn') as HTMLButtonElement;
export const zoomLevel = document.getElementById('zoomLevel')!;
export const nodeActions = document.getElementById('nodeActions')!;
export const selectedNodeBox = document.getElementById('selectedNode')!;
export const nodeInspector = document.getElementById('nodeInspector')!;
export const nodeInspectorTitle = document.getElementById('nodeInspectorTitle')!;
export const nodeTextInput = document.getElementById('nodeTextInput') as HTMLInputElement;
export const nodeTypeRow = document.getElementById('nodeTypeRow')!;
export const nodeTypeInput = document.getElementById('nodeTypeInput') as HTMLInputElement;
export const nodeTypeColorRow = document.getElementById('nodeTypeColorRow')!;
export const nodeTypeColorInput = document.getElementById('nodeTypeColorInput') as HTMLInputElement;
export const nodeInspectorDismissBtn = document.getElementById('nodeInspectorDismissBtn')!;
export const destinationRow = document.getElementById('destinationRow')!;
export const destinationSelect = document.getElementById('destinationSelect') as HTMLSelectElement;
export const nodeInspectorActions = document.getElementById('nodeInspectorActions')!;
export const nodeInspectorControls = document.getElementById('nodeInspectorControls')!;
export const nodeInspectorRemovalPreview = document.getElementById('nodeInspectorRemovalPreview')!;
