flowchart TD
  RAISE_ISSUE[Other side raises an issue]
  SELF_LISTEN["Me: Listen"]
  SELF_TAKE_NOTES["Me: take notes"]

  Q_THEM_DONE_SPEAKING{"in my head: are they done speaking"?}
  Q_THEM_DONE_SPEAKING_Y[Yes]
  Q_THEM_DONE_SPEAKING_N[No]

  Q_ANYTHING_I_DO_NOT_UNDERSTAND["in my head: is there anything said that I don't understand?"]
  Q_ANYTHING_I_DO_NOT_UNDERSTAND_Y[Yes]
  Q_ANYTHING_I_DO_NOT_UNDERSTAND_N[No]

  Q_CLARIFY_ISSUE_COUNT{"how many times have I asked them to clarify ___?"}
  Q_CLARIFY_ISSUE_COUNT_MULTIPLE[Once or more]
  Q_CLARIFY_ISSUE_COUNT_NONE[I haven't yet]

  SELF_ASK_CLARIFYING_QUESTIONS["ask them: I want to understand ___ better. <br/> Can you say more?"]
  Q_SAY_MORE_TO_CLARIFY{"did they agree to say more?"}
  Q_SAY_MORE_TO_CLARIFY_Y[Yes]
  Q_SAY_MORE_TO_CLARIFY_N[No]

  SELF_REFLECT_ON_ISSUE["Me: (in my head) reflect on what they said on my notes"]

  Q_INTERNAL_UNDERSTANDING{"Me: ask self 'Do I understand their issue enough to restate it to them'?"}
  Q_INTERNAL_UNDERSTANDING_Y[Yes]
  Q_INTERNAL_UNDERSTANDING_N[No]

  SELF_RESTATE_ISSUE["Me: read notes to them for confirmation of understanding"]
  
  Q_UNDERSTANDING_ISSUE{"Me: ask them: 'Is my understanding correct?'"}
  Q_UNDERSTANDING_ISSUE_Y[Yes]
  Q_UNDERSTANDING_ISSUE_N[No]
  
  SELF_CHECK_EMPATHY_GOAL[Me: Goal: Empathy]
  
  Q_FEELING_EMPATHY{"Me: ask self 'Do I feel genuine empathy?'"}
  Q_FEELING_EMPATHY_Y[Yes]
  Q_FEELING_EMPATHY_N[No]
  
  SELF_LACK_EMPATHY_ASK["Me: ask them for an impact statement"]
  
  Q_THEIR_IMPACT_STATEMENT{"Did they provide an impact statement"}
  Q_THEIR_IMPACT_STATEMENT_Y[Yes]
  Q_THEIR_IMPACT_STATEMENT_N[No]
  
  SELF_CREATE_SYNTHETIC_IMPACT_STATEMENT["self: draft my own impact statement of what they felt"]
  
  Q_SYNTHETIC_IMPACT_STATEMENT_SHARE{"Me: ask them: 'can I share how I think you felt?'"}
  Q_SYNTHETIC_IMPACT_STATEMENT_SHARE_Y[Yes]
  Q_SYNTHETIC_IMPACT_STATEMENT_SHARE_N[No]
  
  Q_SYNTHETIC_IMPACT_STATEMENT_ACCURACY{"Me: ask them 'Is my understanding of how you felt accurate'?"}
  Q_SYNTHETIC_IMPACT_STATEMENT_ACCURACY_Y[Yes]
  Q_SYNTHETIC_IMPACT_STATEMENT_ACCURACY_N[No]
  
  SELF_CHECK_REGRET_GOAL[Me: Goal: Feel Regret]
  
  Q_FEELING_REGRET{"Me: ask self 'Do I feel genuine regret?'"}
  Q_FEELING_REGRET_Y[Yes]
  Q_FEELING_REGRET_N[No]
  
  SELF_SPOT_MY_PATTERNS[Me: Goal: Understand my patterns]
  SELF_FIND_NEW_PATTERN["(in my head)What am I going to do differently"]
  SELF_EXPRESS_NEW_PATTERN["Communicate: 'here is what I am going to do differently"]

RAISE_ISSUE --> SELF_LISTEN --> SELF_TAKE_NOTES --> Q_THEM_DONE_SPEAKING
Q_THEM_DONE_SPEAKING --> Q_THEM_DONE_SPEAKING_Y --> Q_ANYTHING_I_DO_NOT_UNDERSTAND
Q_THEM_DONE_SPEAKING --> Q_THEM_DONE_SPEAKING_N --> SELF_LISTEN

Q_ANYTHING_I_DO_NOT_UNDERSTAND --> Q_ANYTHING_I_DO_NOT_UNDERSTAND_Y --> Q_CLARIFY_ISSUE_COUNT
Q_CLARIFY_ISSUE_COUNT --> Q_CLARIFY_ISSUE_COUNT_NONE --> SELF_ASK_CLARIFYING_QUESTIONS
Q_CLARIFY_ISSUE_COUNT --> Q_CLARIFY_ISSUE_COUNT_MULTIPLE --> SELF_REFLECT_ON_ISSUE

Q_ANYTHING_I_DO_NOT_UNDERSTAND --> Q_ANYTHING_I_DO_NOT_UNDERSTAND_N --> SELF_RESTATE_ISSUE

Q_INTERNAL_UNDERSTANDING --> Q_INTERNAL_UNDERSTANDING_Y --> SELF_RESTATE_ISSUE
Q_INTERNAL_UNDERSTANDING --> Q_INTERNAL_UNDERSTANDING_N --> Q_CLARIFY_ISSUE_COUNT

SELF_ASK_CLARIFYING_QUESTIONS --> Q_SAY_MORE_TO_CLARIFY
Q_SAY_MORE_TO_CLARIFY --> Q_SAY_MORE_TO_CLARIFY_Y --> SELF_TAKE_NOTES
Q_SAY_MORE_TO_CLARIFY --> Q_SAY_MORE_TO_CLARIFY_N --> SELF_REFLECT_ON_ISSUE

SELF_REFLECT_ON_ISSUE --> Q_INTERNAL_UNDERSTANDING

SELF_RESTATE_ISSUE --> Q_UNDERSTANDING_ISSUE
Q_UNDERSTANDING_ISSUE --> Q_UNDERSTANDING_ISSUE_Y --> SELF_CHECK_EMPATHY_GOAL
Q_UNDERSTANDING_ISSUE --> Q_UNDERSTANDING_ISSUE_N --> SELF_ASK_CLARIFYING_QUESTIONS

SELF_CHECK_EMPATHY_GOAL --> Q_FEELING_EMPATHY 
Q_FEELING_EMPATHY --> Q_FEELING_EMPATHY_Y --> SELF_CHECK_EMPATHY_GOAL
Q_FEELING_EMPATHY --> Q_FEELING_EMPATHY_N --> SELF_LACK_EMPATHY_ASK

SELF_LACK_EMPATHY_ASK --> Q_THEIR_IMPACT_STATEMENT
Q_THEIR_IMPACT_STATEMENT --> Q_THEIR_IMPACT_STATEMENT_Y --> SELF_CHECK_EMPATHY_GOAL
Q_THEIR_IMPACT_STATEMENT --> Q_THEIR_IMPACT_STATEMENT_N --> SELF_CREATE_SYNTHETIC_IMPACT_STATEMENT

SELF_CREATE_SYNTHETIC_IMPACT_STATEMENT --> Q_SYNTHETIC_IMPACT_STATEMENT_SHARE
Q_SYNTHETIC_IMPACT_STATEMENT_SHARE --> Q_SYNTHETIC_IMPACT_STATEMENT_SHARE_Y
Q_SYNTHETIC_IMPACT_STATEMENT_SHARE --> Q_SYNTHETIC_IMPACT_STATEMENT_SHARE_N

SELF_CHECK_EMPATHY_GOAL
SELF_CHECK_EMPATHY_GOAL --> Q_FEELING_REGRET
SELF_CHECK_EMPATHY_GOAL --> SELF_SPOT_MY_PATTERNS
SELF_SPOT_MY_PATTERNS --> SELF_FIND_NEW_PATTERN
SELF_FIND_NEW_PATTERN --> SELF_EXPRESS_NEW_PATTERN