flowchart TD
  B_A[financial investment]
  B_B[what's the cost?]
  B_C[Do we have enough money?]
  Q_CHOICE_C_Y[Yes]
  Q_CHOICE_C_N[No]
  Q_NEED_MONEY_ROUTE{What is the fastest way to get the money?}
B_E_BORROW[Borrow from someone]
B_E_NEW_JOB["get a (better) job"]
B_E_SECOND_JOB[Get a second job]
B_E_JOB_PROMOTION[get a promotion]
  Q_ARE_TERMS_REASONABLE{are the terms of the investment reasonable?}

Q_CHOICE_ARE_TERMS_REASONABLE_Y[Yes]
Q_CHOICE_ARE_TERMS_REASONABLE_N[No]

B_A --> B_B --> B_C
B_C --> Q_CHOICE_C_Y --> Q_ARE_TERMS_REASONABLE
B_C --> Q_CHOICE_C_N --> Q_NEED_MONEY_ROUTE

Q_NEED_MONEY_ROUTE --> B_E_BORROW
Q_NEED_MONEY_ROUTE --> B_E_NEW_JOB
Q_NEED_MONEY_ROUTE --> B_E_JOB_PROMOTION
Q_NEED_MONEY_ROUTE --> B_E_SECOND_JOB

Q_ARE_TERMS_REASONABLE --> Q_CHOICE_ARE_TERMS_REASONABLE_Y

Q_ARE_TERMS_REASONABLE --> Q_CHOICE_ARE_TERMS_REASONABLE_N